[project]
name = "langchain_experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "deepagents>=0.5.6",
    "langchain-daytona>=0.0.5",
    "langsmith>=0.7.37",
    "python-dotenv>=1.2.2",
    "slack-sdk>=3.41.0",
    "langchain-google-genai>=4.2.2",
    "tavily-python>=0.7.24",
    "httpx>=0.28.1",
    "markdownify>=1.2.2",
    "langchain-community>=0.4.1",
    "pypdf>=6.11.0",
    "qdrant-client[fastembed]>=1.18.0",
    "langchain-qdrant>=1.1.0",
    "bs4>=0.0.2",
    "langgraph>=1.2.5",
    "langgraph-cli[inmem]>=0.4.26",
    "elevenlabs>=2.49.0",
    "fastapi>=0.136.1",
    "granian>=2.7.4",
    "langchain-openai>=1.2.2",
    "langgraph-checkpoint>=4.1.0",
    "ipython>=9.14.1",
]
